# docker-compose.yml
version: '3.3'

services:
  microshop-user-service:
    depends_on:
      - microshop-user-db
    build: ./user-service
    ports:
      - 9092:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "microshop-user-db:3306"
      DB_NAME: "microshop_user"
      DB_USER: "test"
      DB_PASSWORD: "test"

  microshop-user-db:
    image: mysql:8.0.18
    container_name: microshop-user-db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "microshop_user"
      MYSQL_ROOT_PASSWORD: "root"

  microshop-micro-api:
    image: microhq/miro:latest
    environment:
      MICRO_REGISTRY: "mdns"
    links:
      - microshop-user-service
    ports:
      - 8080:8080
    command: api --handler=rpc --namespace=microshop.service

  microshop-user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

volumes:
  db_data: {}